CREATE TABLE [User] (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(255) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    Role NVARCHAR(50) NOT NULL
);

CREATE TABLE Product (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Brand NVARCHAR(255) NOT NULL,
    Value FLOAT NOT NULL,
    BarCode BIGINT NOT NULL
);

CREATE TABLE [Order] (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    Products NVARCHAR(MAX) NOT NULL,
    TotalPrice FLOAT NOT NULL,
    PaymentInfo NVARCHAR(MAX) NOT NULL
);